services:
    api:
        build:
            context: ./api
            target: dev
        volumes:
            - ./api:/home/app
        command: npm start
        networks:
            - backend
        ports:
            - 5000:80
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=nhei
            - MONGO_INITDB_ROOT_PASSWORD=nhei
        volumes:
            - mongo:/data/db
        networks:
            - backend
    redis:
        image: redis:alpine
        command: >
            --requirepass nhei
        volumes:
            - redis:/data
        networks:
            - backend
volumes:
    mongo:
        external: false
        name: nhei_mongo
    redis:
        external: false
        name: nhei_redis

networks:
    backend:
